// Mock Certificates Data for U-Exam Platform

export type CertificateStatus = "ACTIVE" | "EXPIRED" | "REVOKED";

export type MockCertificate = {
  id: string;
  certificateNumber: string;
  candidateId: string;
  candidateName: string;
  candidateEmail: string;
  examId: string;
  examName: string;
  score: number;
  totalPoints: number;
  percentage: number;
  issueDate: string;
  expiryDate: string;
  status: CertificateStatus;
  verificationCode: string;
  verificationUrl: string;
  badgeImageUrl: string;
  pdfUrl: string;
  issuedBy: string;
  tenantId: string;
};

export const MOCK_CERTIFICATES: MockCertificate[] = [
  {
    id: "cert_001",
    certificateNumber: "UEXAM-CYBER-2025-00148",
    candidateId: "usr_011",
    candidateName: "ณัฐพล ศิริวัฒน์",
    candidateEmail: "nattapol.s@gmail.com",
    examId: "exam_004",
    examName: "ทดสอบความรู้ Cybersecurity Essentials",
    score: 68,
    totalPoints: 80,
    percentage: 85,
    issueDate: "2025-12-16T10:00:00.000Z",
    expiryDate: "2027-12-16T10:00:00.000Z",
    status: "ACTIVE",
    verificationCode: "VRF-CYB-A7B3C9D1",
    verificationUrl: "https://uexam.io/verify/VRF-CYB-A7B3C9D1",
    badgeImageUrl: "/images/badges/cybersecurity-essentials.png",
    pdfUrl: "/certificates/UEXAM-CYBER-2025-00148.pdf",
    issuedBy: "TechCorp Certification Authority",
    tenantId: "tenant_001",
  },
  {
    id: "cert_002",
    certificateNumber: "UEXAM-CYBER-2025-00152",
    candidateId: "usr_013",
    candidateName: "วรเมธ ทองคำ",
    candidateEmail: "woramet.t@hotmail.com",
    examId: "exam_004",
    examName: "ทดสอบความรู้ Cybersecurity Essentials",
    score: 72,
    totalPoints: 80,
    percentage: 90,
    issueDate: "2025-12-16T10:00:00.000Z",
    expiryDate: "2027-12-16T10:00:00.000Z",
    status: "ACTIVE",
    verificationCode: "VRF-CYB-E4F5G6H2",
    verificationUrl: "https://uexam.io/verify/VRF-CYB-E4F5G6H2",
    badgeImageUrl: "/images/badges/cybersecurity-essentials.png",
    pdfUrl: "/certificates/UEXAM-CYBER-2025-00152.pdf",
    issuedBy: "TechCorp Certification Authority",
    tenantId: "tenant_001",
  },
  {
    id: "cert_003",
    certificateNumber: "UEXAM-CYBER-2025-00156",
    candidateId: "usr_015",
    candidateName: "ชาญชัย บุญเรือง",
    candidateEmail: "chanchai.b@gmail.com",
    examId: "exam_004",
    examName: "ทดสอบความรู้ Cybersecurity Essentials",
    score: 56,
    totalPoints: 80,
    percentage: 70,
    issueDate: "2025-12-16T10:00:00.000Z",
    expiryDate: "2027-12-16T10:00:00.000Z",
    status: "ACTIVE",
    verificationCode: "VRF-CYB-I7J8K9L3",
    verificationUrl: "https://uexam.io/verify/VRF-CYB-I7J8K9L3",
    badgeImageUrl: "/images/badges/cybersecurity-essentials.png",
    pdfUrl: "/certificates/UEXAM-CYBER-2025-00156.pdf",
    issuedBy: "TechCorp Certification Authority",
    tenantId: "tenant_001",
  },
  {
    id: "cert_004",
    certificateNumber: "UEXAM-SE-2026-00092",
    candidateId: "usr_011",
    candidateName: "ณัฐพล ศิริวัฒน์",
    candidateEmail: "nattapol.s@gmail.com",
    examId: "exam_005",
    examName: "Software Engineering Principles",
    score: 81,
    totalPoints: 90,
    percentage: 90,
    issueDate: "2026-01-21T10:00:00.000Z",
    expiryDate: "2028-01-21T10:00:00.000Z",
    status: "ACTIVE",
    verificationCode: "VRF-SE-M1N2O3P4",
    verificationUrl: "https://uexam.io/verify/VRF-SE-M1N2O3P4",
    badgeImageUrl: "/images/badges/software-engineering.png",
    pdfUrl: "/certificates/UEXAM-SE-2026-00092.pdf",
    issuedBy: "TechCorp Certification Authority",
    tenantId: "tenant_001",
  },
  {
    id: "cert_005",
    certificateNumber: "UEXAM-SE-2026-00095",
    candidateId: "usr_012",
    candidateName: "ปิยะธิดา แก้วมณี",
    candidateEmail: "piyathida.k@gmail.com",
    examId: "exam_005",
    examName: "Software Engineering Principles",
    score: 72,
    totalPoints: 90,
    percentage: 80,
    issueDate: "2026-01-21T10:00:00.000Z",
    expiryDate: "2028-01-21T10:00:00.000Z",
    status: "ACTIVE",
    verificationCode: "VRF-SE-Q5R6S7T8",
    verificationUrl: "https://uexam.io/verify/VRF-SE-Q5R6S7T8",
    badgeImageUrl: "/images/badges/software-engineering.png",
    pdfUrl: "/certificates/UEXAM-SE-2026-00095.pdf",
    issuedBy: "TechCorp Certification Authority",
    tenantId: "tenant_001",
  },
  {
    id: "cert_006",
    certificateNumber: "UEXAM-SE-2026-00098",
    candidateId: "usr_014",
    candidateName: "กัลยา พงษ์พิพัฒน์",
    candidateEmail: "kanlaya.p@outlook.com",
    examId: "exam_005",
    examName: "Software Engineering Principles",
    score: 63,
    totalPoints: 90,
    percentage: 70,
    issueDate: "2026-01-21T10:00:00.000Z",
    expiryDate: "2028-01-21T10:00:00.000Z",
    status: "REVOKED",
    verificationCode: "VRF-SE-U9V0W1X2",
    verificationUrl: "https://uexam.io/verify/VRF-SE-U9V0W1X2",
    badgeImageUrl: "/images/badges/software-engineering.png",
    pdfUrl: "/certificates/UEXAM-SE-2026-00098.pdf",
    issuedBy: "TechCorp Certification Authority",
    tenantId: "tenant_001",
  },
  {
    id: "cert_007",
    certificateNumber: "UEXAM-SE-2026-00101",
    candidateId: "usr_015",
    candidateName: "ชาญชัย บุญเรือง",
    candidateEmail: "chanchai.b@gmail.com",
    examId: "exam_005",
    examName: "Software Engineering Principles",
    score: 54,
    totalPoints: 90,
    percentage: 60,
    issueDate: "2026-01-21T10:00:00.000Z",
    expiryDate: "2028-01-21T10:00:00.000Z",
    status: "ACTIVE",
    verificationCode: "VRF-SE-Y3Z4A5B6",
    verificationUrl: "https://uexam.io/verify/VRF-SE-Y3Z4A5B6",
    badgeImageUrl: "/images/badges/software-engineering.png",
    pdfUrl: "/certificates/UEXAM-SE-2026-00101.pdf",
    issuedBy: "TechCorp Certification Authority",
    tenantId: "tenant_001",
  },
  {
    id: "cert_008",
    certificateNumber: "UEXAM-JAVA-2024-00034",
    candidateId: "usr_011",
    candidateName: "ณัฐพล ศิริวัฒน์",
    candidateEmail: "nattapol.s@gmail.com",
    examId: "exam_legacy_001",
    examName: "Java Programming Certification",
    score: 85,
    totalPoints: 100,
    percentage: 85,
    issueDate: "2024-06-15T10:00:00.000Z",
    expiryDate: "2025-06-15T10:00:00.000Z",
    status: "EXPIRED",
    verificationCode: "VRF-JAVA-C7D8E9F0",
    verificationUrl: "https://uexam.io/verify/VRF-JAVA-C7D8E9F0",
    badgeImageUrl: "/images/badges/java-programming.png",
    pdfUrl: "/certificates/UEXAM-JAVA-2024-00034.pdf",
    issuedBy: "TechCorp Certification Authority",
    tenantId: "tenant_001",
  },
];
