// Mock Exams Data for U-Exam Platform

export type ExamStatus = "DRAFT" | "PUBLISHED" | "ACTIVE" | "COMPLETED";

export type ExamMode = "PUBLIC" | "CORPORATE";

export type MockExam = {
  id: string;
  title: string;
  description: string;
  mode: ExamMode;
  totalQuestions: number;
  totalPoints: number;
  duration: number; // minutes
  passingScore: number; // percentage
  status: ExamStatus;
  scheduledStart: string | null;
  scheduledEnd: string | null;
  attemptLimit: number;
  shuffleQuestions: boolean;
  shuffleOptions: boolean;
  showResult: boolean;
  antiCheatEnabled: boolean;
  categories: string[];
  creatorId: string;
  creatorName: string;
  tenantId: string;
  registeredCount: number;
  completedCount: number;
  createdAt: string;
  updatedAt: string;
};

export const MOCK_EXAMS: MockExam[] = [
  {
    id: "exam_001",
    title: "ใบรับรองวิชาชีพ IT Fundamentals",
    description:
      "การสอบใบรับรองความรู้พื้นฐานด้านเทคโนโลยีสารสนเทศ ครอบคลุมเนื้อหาเครือข่าย, ฐานข้อมูล, การเขียนโปรแกรม และความปลอดภัยทางไซเบอร์",
    mode: "PUBLIC",
    totalQuestions: 60,
    totalPoints: 100,
    duration: 120,
    passingScore: 70,
    status: "ACTIVE",
    scheduledStart: "2026-03-15T09:00:00.000Z",
    scheduledEnd: "2026-03-15T11:00:00.000Z",
    attemptLimit: 2,
    shuffleQuestions: true,
    shuffleOptions: true,
    showResult: true,
    antiCheatEnabled: true,
    categories: [
      "เครือข่ายคอมพิวเตอร์",
      "ฐานข้อมูล",
      "การเขียนโปรแกรม",
      "Cybersecurity",
    ],
    creatorId: "usr_004",
    creatorName: "ดร.นภา วงศ์ประเสริฐ",
    tenantId: "tenant_001",
    registeredCount: 245,
    completedCount: 0,
    createdAt: "2025-11-01T10:00:00.000Z",
    updatedAt: "2026-02-20T14:00:00.000Z",
  },
  {
    id: "exam_002",
    title: "Web Development Professional Certification",
    description:
      "การสอบใบรับรอง Web Developer ระดับมืออาชีพ ครอบคลุม HTML, CSS, JavaScript, React, Node.js และ Database",
    mode: "PUBLIC",
    totalQuestions: 80,
    totalPoints: 150,
    duration: 180,
    passingScore: 75,
    status: "PUBLISHED",
    scheduledStart: "2026-04-20T09:00:00.000Z",
    scheduledEnd: "2026-04-20T12:00:00.000Z",
    attemptLimit: 1,
    shuffleQuestions: true,
    shuffleOptions: true,
    showResult: false,
    antiCheatEnabled: true,
    categories: ["การพัฒนาเว็บ", "JavaScript", "React", "Node.js"],
    creatorId: "usr_004",
    creatorName: "ดร.นภา วงศ์ประเสริฐ",
    tenantId: "tenant_001",
    registeredCount: 189,
    completedCount: 0,
    createdAt: "2025-12-01T09:00:00.000Z",
    updatedAt: "2026-01-15T11:00:00.000Z",
  },
  {
    id: "exam_003",
    title: "Data Science & Analytics Certification",
    description:
      "การสอบใบรับรองทักษะ Data Science ครอบคลุม Python, Statistics, Machine Learning และ Data Visualization",
    mode: "PUBLIC",
    totalQuestions: 50,
    totalPoints: 100,
    duration: 150,
    passingScore: 65,
    status: "PUBLISHED",
    scheduledStart: "2026-05-10T09:00:00.000Z",
    scheduledEnd: "2026-05-10T11:30:00.000Z",
    attemptLimit: 2,
    shuffleQuestions: true,
    shuffleOptions: false,
    showResult: true,
    antiCheatEnabled: true,
    categories: ["Data Science", "Python", "Machine Learning", "Statistics"],
    creatorId: "usr_005",
    creatorName: "อรุณ แสงทอง",
    tenantId: "tenant_001",
    registeredCount: 120,
    completedCount: 0,
    createdAt: "2026-01-10T10:00:00.000Z",
    updatedAt: "2026-02-28T15:00:00.000Z",
  },
  {
    id: "exam_004",
    title: "ทดสอบความรู้ Cybersecurity Essentials",
    description:
      "การสอบประเมินความรู้ด้านความมั่นคงปลอดภัยทางไซเบอร์ ครอบคลุม Network Security, Cryptography, Incident Response",
    mode: "PUBLIC",
    totalQuestions: 40,
    totalPoints: 80,
    duration: 90,
    passingScore: 70,
    status: "COMPLETED",
    scheduledStart: "2025-12-15T09:00:00.000Z",
    scheduledEnd: "2025-12-15T10:30:00.000Z",
    attemptLimit: 1,
    shuffleQuestions: true,
    shuffleOptions: true,
    showResult: true,
    antiCheatEnabled: true,
    categories: ["Cybersecurity", "Network Security", "Cryptography"],
    creatorId: "usr_004",
    creatorName: "ดร.นภา วงศ์ประเสริฐ",
    tenantId: "tenant_001",
    registeredCount: 156,
    completedCount: 148,
    createdAt: "2025-09-01T10:00:00.000Z",
    updatedAt: "2025-12-16T08:00:00.000Z",
  },
  {
    id: "exam_005",
    title: "Software Engineering Principles",
    description:
      "การสอบหลักการวิศวกรรมซอฟต์แวร์ ครอบคลุม Design Patterns, SOLID Principles, Agile, CI/CD",
    mode: "PUBLIC",
    totalQuestions: 45,
    totalPoints: 90,
    duration: 120,
    passingScore: 60,
    status: "COMPLETED",
    scheduledStart: "2026-01-20T09:00:00.000Z",
    scheduledEnd: "2026-01-20T11:00:00.000Z",
    attemptLimit: 2,
    shuffleQuestions: true,
    shuffleOptions: true,
    showResult: true,
    antiCheatEnabled: false,
    categories: ["วิศวกรรมซอฟต์แวร์", "Design Pattern", "Agile"],
    creatorId: "usr_005",
    creatorName: "อรุณ แสงทอง",
    tenantId: "tenant_001",
    registeredCount: 98,
    completedCount: 92,
    createdAt: "2025-10-15T09:00:00.000Z",
    updatedAt: "2026-01-21T10:00:00.000Z",
  },
  {
    id: "exam_006",
    title: "TechCorp Internal - Q1 2026 Assessment",
    description:
      "การทดสอบประเมินความรู้ประจำไตรมาส Q1 สำหรับพนักงานฝ่ายพัฒนาซอฟต์แวร์ TechCorp",
    mode: "CORPORATE",
    totalQuestions: 30,
    totalPoints: 60,
    duration: 60,
    passingScore: 50,
    status: "ACTIVE",
    scheduledStart: "2026-03-12T09:00:00.000Z",
    scheduledEnd: "2026-03-14T17:00:00.000Z",
    attemptLimit: 1,
    shuffleQuestions: true,
    shuffleOptions: true,
    showResult: true,
    antiCheatEnabled: false,
    categories: ["Internal Assessment", "Software Development"],
    creatorId: "usr_004",
    creatorName: "ดร.นภา วงศ์ประเสริฐ",
    tenantId: "tenant_001",
    registeredCount: 45,
    completedCount: 28,
    createdAt: "2026-02-01T10:00:00.000Z",
    updatedAt: "2026-03-10T08:00:00.000Z",
  },
  {
    id: "exam_007",
    title: "Cloud Computing Fundamentals",
    description:
      "การสอบใบรับรองความรู้ Cloud Computing ครอบคลุม AWS, Azure, GCP, Containerization และ DevOps",
    mode: "PUBLIC",
    totalQuestions: 55,
    totalPoints: 110,
    duration: 120,
    passingScore: 70,
    status: "DRAFT",
    scheduledStart: null,
    scheduledEnd: null,
    attemptLimit: 2,
    shuffleQuestions: true,
    shuffleOptions: true,
    showResult: true,
    antiCheatEnabled: true,
    categories: ["Cloud Computing", "AWS", "DevOps", "Container"],
    creatorId: "usr_005",
    creatorName: "อรุณ แสงทอง",
    tenantId: "tenant_001",
    registeredCount: 0,
    completedCount: 0,
    createdAt: "2026-03-01T10:00:00.000Z",
    updatedAt: "2026-03-08T16:00:00.000Z",
  },
  {
    id: "exam_008",
    title: "Project Management Professional (PMP) Prep",
    description:
      "ข้อสอบเตรียมความพร้อมสำหรับ PMP ครอบคลุม Project Initiation, Planning, Execution, Monitoring, Closing",
    mode: "PUBLIC",
    totalQuestions: 100,
    totalPoints: 200,
    duration: 240,
    passingScore: 60,
    status: "PUBLISHED",
    scheduledStart: "2026-06-01T08:00:00.000Z",
    scheduledEnd: "2026-06-01T12:00:00.000Z",
    attemptLimit: 3,
    shuffleQuestions: true,
    shuffleOptions: true,
    showResult: false,
    antiCheatEnabled: true,
    categories: ["Project Management", "PMP", "Agile", "Waterfall"],
    creatorId: "usr_004",
    creatorName: "ดร.นภา วงศ์ประเสริฐ",
    tenantId: "tenant_001",
    registeredCount: 67,
    completedCount: 0,
    createdAt: "2026-02-15T10:00:00.000Z",
    updatedAt: "2026-03-05T11:00:00.000Z",
  },
  {
    id: "exam_009",
    title: "TechCorp Onboarding - Technical Skills",
    description:
      "แบบทดสอบทักษะทางเทคนิคสำหรับพนักงานใหม่ TechCorp ครอบคลุม Git, Docker, API Design, Testing",
    mode: "CORPORATE",
    totalQuestions: 25,
    totalPoints: 50,
    duration: 45,
    passingScore: 60,
    status: "ACTIVE",
    scheduledStart: "2026-03-01T09:00:00.000Z",
    scheduledEnd: "2026-03-31T17:00:00.000Z",
    attemptLimit: 3,
    shuffleQuestions: false,
    shuffleOptions: true,
    showResult: true,
    antiCheatEnabled: false,
    categories: ["Onboarding", "Git", "Docker", "API"],
    creatorId: "usr_005",
    creatorName: "อรุณ แสงทอง",
    tenantId: "tenant_001",
    registeredCount: 12,
    completedCount: 8,
    createdAt: "2026-02-20T09:00:00.000Z",
    updatedAt: "2026-03-09T14:00:00.000Z",
  },
  {
    id: "exam_010",
    title: "AI & Machine Learning Advanced",
    description:
      "การสอบใบรับรอง AI/ML ระดับสูง ครอบคลุม Deep Learning, NLP, Computer Vision, MLOps และ Ethics in AI",
    mode: "PUBLIC",
    totalQuestions: 70,
    totalPoints: 140,
    duration: 180,
    passingScore: 65,
    status: "DRAFT",
    scheduledStart: null,
    scheduledEnd: null,
    attemptLimit: 1,
    shuffleQuestions: true,
    shuffleOptions: true,
    showResult: false,
    antiCheatEnabled: true,
    categories: ["AI", "Machine Learning", "Deep Learning", "NLP"],
    creatorId: "usr_004",
    creatorName: "ดร.นภา วงศ์ประเสริฐ",
    tenantId: "tenant_001",
    registeredCount: 0,
    completedCount: 0,
    createdAt: "2026-03-05T10:00:00.000Z",
    updatedAt: "2026-03-09T15:30:00.000Z",
  },
];
