// Mock Registrations Data for U-Exam Platform

export type RegistrationStatus =
  | "CONFIRMED"
  | "PENDING"
  | "CANCELLED"
  | "WAITING_LIST";

export type PaymentStatus = "PAID" | "PENDING" | "REFUNDED" | "WAIVED";

export type MockRegistration = {
  id: string;
  candidateId: string;
  candidateName: string;
  candidateEmail: string;
  examId: string;
  examName: string;
  centerId: string;
  centerName: string;
  roomId: string | null;
  seatNumber: string | null;
  registrationDate: string;
  examDate: string;
  status: RegistrationStatus;
  paymentStatus: PaymentStatus;
  amount: number;
  notes: string | null;
};

export const MOCK_REGISTRATIONS: MockRegistration[] = [
  {
    id: "reg_001",
    candidateId: "usr_011",
    candidateName: "ณัฐพล ศิริวัฒน์",
    candidateEmail: "nattapol.s@gmail.com",
    examId: "exam_001",
    examName: "ใบรับรองวิชาชีพ IT Fundamentals",
    centerId: "center_001",
    centerName: "ศูนย์สอบ U-Exam สยามสแควร์",
    roomId: "room_001",
    seatNumber: "A1-12",
    registrationDate: "2026-02-01T10:30:00.000Z",
    examDate: "2026-03-15T09:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    amount: 2500,
    notes: null,
  },
  {
    id: "reg_002",
    candidateId: "usr_012",
    candidateName: "ปิยะธิดา แก้วมณี",
    candidateEmail: "piyathida.k@gmail.com",
    examId: "exam_001",
    examName: "ใบรับรองวิชาชีพ IT Fundamentals",
    centerId: "center_001",
    centerName: "ศูนย์สอบ U-Exam สยามสแควร์",
    roomId: "room_001",
    seatNumber: "A1-15",
    registrationDate: "2026-02-03T14:20:00.000Z",
    examDate: "2026-03-15T09:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    amount: 2500,
    notes: null,
  },
  {
    id: "reg_003",
    candidateId: "usr_013",
    candidateName: "วรเมธ ทองคำ",
    candidateEmail: "woramet.t@hotmail.com",
    examId: "exam_001",
    examName: "ใบรับรองวิชาชีพ IT Fundamentals",
    centerId: "center_005",
    centerName: "ศูนย์สอบ U-Exam บางนา",
    roomId: "room_011",
    seatNumber: "E1-08",
    registrationDate: "2026-02-10T09:15:00.000Z",
    examDate: "2026-03-15T09:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    amount: 2500,
    notes: null,
  },
  {
    id: "reg_004",
    candidateId: "usr_015",
    candidateName: "ชาญชัย บุญเรือง",
    candidateEmail: "chanchai.b@gmail.com",
    examId: "exam_001",
    examName: "ใบรับรองวิชาชีพ IT Fundamentals",
    centerId: "center_002",
    centerName: "ศูนย์สอบ U-Exam เชียงใหม่",
    roomId: "room_006",
    seatNumber: "C1-22",
    registrationDate: "2026-02-15T11:00:00.000Z",
    examDate: "2026-03-15T09:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    amount: 2500,
    notes: null,
  },
  {
    id: "reg_005",
    candidateId: "usr_014",
    candidateName: "กัลยา พงษ์พิพัฒน์",
    candidateEmail: "kanlaya.p@outlook.com",
    examId: "exam_001",
    examName: "ใบรับรองวิชาชีพ IT Fundamentals",
    centerId: "center_001",
    centerName: "ศูนย์สอบ U-Exam สยามสแควร์",
    roomId: null,
    seatNumber: null,
    registrationDate: "2026-02-28T16:45:00.000Z",
    examDate: "2026-03-15T09:00:00.000Z",
    status: "PENDING",
    paymentStatus: "PENDING",
    amount: 2500,
    notes: "รอชำระเงิน",
  },
  {
    id: "reg_006",
    candidateId: "usr_011",
    candidateName: "ณัฐพล ศิริวัฒน์",
    candidateEmail: "nattapol.s@gmail.com",
    examId: "exam_002",
    examName: "Web Development Professional Certification",
    centerId: "center_001",
    centerName: "ศูนย์สอบ U-Exam สยามสแควร์",
    roomId: "room_002",
    seatNumber: "A2-05",
    registrationDate: "2026-02-20T10:00:00.000Z",
    examDate: "2026-04-20T09:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    amount: 3500,
    notes: null,
  },
  {
    id: "reg_007",
    candidateId: "usr_012",
    candidateName: "ปิยะธิดา แก้วมณี",
    candidateEmail: "piyathida.k@gmail.com",
    examId: "exam_002",
    examName: "Web Development Professional Certification",
    centerId: "center_005",
    centerName: "ศูนย์สอบ U-Exam บางนา",
    roomId: "room_012",
    seatNumber: "E2-18",
    registrationDate: "2026-02-22T13:30:00.000Z",
    examDate: "2026-04-20T09:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    amount: 3500,
    notes: null,
  },
  {
    id: "reg_008",
    candidateId: "usr_013",
    candidateName: "วรเมธ ทองคำ",
    candidateEmail: "woramet.t@hotmail.com",
    examId: "exam_002",
    examName: "Web Development Professional Certification",
    centerId: "center_001",
    centerName: "ศูนย์สอบ U-Exam สยามสแควร์",
    roomId: null,
    seatNumber: null,
    registrationDate: "2026-03-05T09:00:00.000Z",
    examDate: "2026-04-20T09:00:00.000Z",
    status: "WAITING_LIST",
    paymentStatus: "PAID",
    amount: 3500,
    notes: "ห้องสอบเต็ม - อยู่ในรายการรอ ลำดับที่ 3",
  },
  {
    id: "reg_009",
    candidateId: "usr_015",
    candidateName: "ชาญชัย บุญเรือง",
    candidateEmail: "chanchai.b@gmail.com",
    examId: "exam_003",
    examName: "Data Science & Analytics Certification",
    centerId: "center_002",
    centerName: "ศูนย์สอบ U-Exam เชียงใหม่",
    roomId: "room_007",
    seatNumber: "C2-10",
    registrationDate: "2026-03-01T08:30:00.000Z",
    examDate: "2026-05-10T09:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    amount: 3000,
    notes: null,
  },
  {
    id: "reg_010",
    candidateId: "usr_014",
    candidateName: "กัลยา พงษ์พิพัฒน์",
    candidateEmail: "kanlaya.p@outlook.com",
    examId: "exam_003",
    examName: "Data Science & Analytics Certification",
    centerId: "center_003",
    centerName: "ศูนย์สอบ U-Exam ขอนแก่น",
    roomId: null,
    seatNumber: null,
    registrationDate: "2026-03-08T17:00:00.000Z",
    examDate: "2026-05-10T09:00:00.000Z",
    status: "CANCELLED",
    paymentStatus: "REFUNDED",
    amount: 3000,
    notes: "ผู้สมัครขอยกเลิก เนื่องจากติดธุระส่วนตัว",
  },
  {
    id: "reg_011",
    candidateId: "usr_011",
    candidateName: "ณัฐพล ศิริวัฒน์",
    candidateEmail: "nattapol.s@gmail.com",
    examId: "exam_003",
    examName: "Data Science & Analytics Certification",
    centerId: "center_001",
    centerName: "ศูนย์สอบ U-Exam สยามสแควร์",
    roomId: "room_003",
    seatNumber: "B1-01",
    registrationDate: "2026-03-02T11:45:00.000Z",
    examDate: "2026-05-10T09:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    amount: 3000,
    notes: null,
  },
  {
    id: "reg_012",
    candidateId: "usr_012",
    candidateName: "ปิยะธิดา แก้วมณี",
    candidateEmail: "piyathida.k@gmail.com",
    examId: "exam_008",
    examName: "Project Management Professional (PMP) Prep",
    centerId: "center_005",
    centerName: "ศูนย์สอบ U-Exam บางนา",
    roomId: "room_011",
    seatNumber: "E1-30",
    registrationDate: "2026-03-10T09:00:00.000Z",
    examDate: "2026-06-01T08:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    amount: 4500,
    notes: null,
  },
  {
    id: "reg_013",
    candidateId: "usr_013",
    candidateName: "วรเมธ ทองคำ",
    candidateEmail: "woramet.t@hotmail.com",
    examId: "exam_008",
    examName: "Project Management Professional (PMP) Prep",
    centerId: "center_001",
    centerName: "ศูนย์สอบ U-Exam สยามสแควร์",
    roomId: null,
    seatNumber: null,
    registrationDate: "2026-03-09T15:20:00.000Z",
    examDate: "2026-06-01T08:00:00.000Z",
    status: "PENDING",
    paymentStatus: "PENDING",
    amount: 4500,
    notes: "รอชำระเงินภายใน 7 วัน",
  },
  {
    id: "reg_014",
    candidateId: "usr_015",
    candidateName: "ชาญชัย บุญเรือง",
    candidateEmail: "chanchai.b@gmail.com",
    examId: "exam_008",
    examName: "Project Management Professional (PMP) Prep",
    centerId: "center_002",
    centerName: "ศูนย์สอบ U-Exam เชียงใหม่",
    roomId: null,
    seatNumber: null,
    registrationDate: "2026-03-10T07:00:00.000Z",
    examDate: "2026-06-01T08:00:00.000Z",
    status: "WAITING_LIST",
    paymentStatus: "PAID",
    amount: 4500,
    notes: "ห้องสอบเชียงใหม่เต็ม - รอลำดับที่ 1",
  },
  {
    id: "reg_015",
    candidateId: "usr_011",
    candidateName: "ณัฐพล ศิริวัฒน์",
    candidateEmail: "nattapol.s@gmail.com",
    examId: "exam_004",
    examName: "ทดสอบความรู้ Cybersecurity Essentials",
    centerId: "center_001",
    centerName: "ศูนย์สอบ U-Exam สยามสแควร์",
    roomId: "room_002",
    seatNumber: "A2-12",
    registrationDate: "2025-11-01T10:00:00.000Z",
    examDate: "2025-12-15T09:00:00.000Z",
    status: "CONFIRMED",
    paymentStatus: "PAID",
    amount: 2000,
    notes: "สอบเสร็จแล้ว",
  },
];
